---
name: 'Foobar'
description: 'Foobar'
inputs:
  environment:
    description: 'The environment to run the terraform plan and apply against'
    required: true
    default: 'sandbox'
  approver_required:
    description: 'If true, then the terraform plan will require approval before running terraform apply'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: ls
      run: ls -la
      shell: bash
      working-directory: ${{ inputs.environment }}/vault
    - name: terraform init
      run: terraform init -no-color
      shell: bash
      working-directory: ${{ inputs.environment }}/vault
    # - name: approve
    #   if: ${{ github.event.inputs.approver_required == 'true' }}
    #   uses: actions/request-approval@v2
    #   with:
    #     reviewers: octocat #TODO: change to some other approver
    - name: deploy
      run: echo "deploying to ${{ inputs.environment }}"
      shell: bash
      working-directory: ${{ inputs.environment }}/vault
