---
name: 'Terraform'
description: 'Run terraform plan and apply'
inputs:
  environment:
    description: 'The environment to run the terraform plan and apply against'
    required: true
    default: 'sandbox'
  approver_required:
    description: 'If true, then the terraform plan will require approval before running terraform apply'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: ls
      run: ls -la
      shell: bash
      working-directory: ${{ inputs.environment }}/vault
    - name: terraform init
      run: terraform init -no-color
      shell: bash
      working-directory: ${{ inputs.environment }}/vault
    - name: terraform plan
      id: plan
      run: terraform plan -no-color -out=terraform.plan
      shell: bash
      working-directory: ${{ inputs.environment }}/vault
      continue-on-error: true

    #TODO: this step isn't running
    - uses: actions/github-script@v6
      if: ${{ github.event_name == 'pull_request' }}
      env:
        PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
      with:
        script: |
          const output = `### Environment: \`${{ inputs.environment }}\`
          #### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
          #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
          #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
          #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

          <details><summary>Show Plan</summary>

          \`\`\`\n
          ${process.env.PLAN}
          \`\`\`

          </details>

          *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `${output}`
          })
    - name: Terraform Plan Status
      if: steps.plan.outcome == 'failure'
      run: exit 1
      shell: bash
          
    # - name: approve
    #   if: ${{ github.event.inputs.approver_required == 'true' }}
    #   uses: actions/request-approval@v2
    #   with:
    #     reviewers: octocat #TODO: change to some other approver
    
    - name: Terraform Apply
      # only on main branch
      if: ${{ github.ref == 'refs/heads/main' }}
      run: terraform apply -no-color terraform.plan
      shell: bash
      working-directory: ${{ inputs.environment }}/vault
