# Find all .tf files and run terraform fmt

name: Terraform Format

on:
  push:
    branches:
      - '!main'
    paths:
      - '**.tf'
jobs:
  terraform_fmt:
    runs-on: ubuntu-latest
    name: Terraform Format
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7
      - name: Terraform Format
        run: terraform fmt -recursive -no-color
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          message: "Format Terraform Templates"
          add: "*.tf"