# Validate terraform files

name: Terraform Validate

on:
  push:
    # branches:
    #   - '!main'
    # paths:
    #   - '**.tf'

jobs:
  terraform_validate:
    runs-on: ubuntu-latest
    name: Terraform Validate
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7
      - name: Terraform Validate
        run: terraform validate -no-color
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          message: "Format Terraform Templates"
          add: "*.tf"