# Run terraform validate . -no-color

name: Terraform Validate

on:
  push:
    branches:
      - '*'
      - '!main'
    # paths:
    #   - '**.tf'

jobs:
  terraform_validate:
    runs-on: ubuntu-latest
    name: Terraform Validate
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7
      # Find every main.tf file in the repo and run terraform validate on it
      - name: Terraform Validate
        run: |
          find . -name "*.tf" -exec dirname {} \; | while read -r dir; do
            echo "Validating ${dir}"
            cd ${dir}
            terraform init -backend=false
            terraform validate . -no-color
          done