# Run terraform validate . -no-color

name: Terraform Validate

on:
  push:
    branches:
      - '*'
      - '!main'
    paths:
      - '**.tf'

jobs:
  terraform_validate:
    runs-on: ubuntu-latest
    name: Terraform Validate
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.7
      - name: Terraform Validate
        run: |
          find . -name "*.tf" -type f -exec dirname {} \; | sort -u | while read -r dir; do
            echo "Running terraform validate in $dir"
            terraform validate "$dir" -no-color
          done
        shell: bash